/*
 * Copyright (c) 2019 João Pedro Martins Neves (shivayl) - All Rights Reserved.
 *
 * ClassStudio is licensed under the GNU Lesser General Public License (LGPL),
 * version 3, located in the root of this project, under the name "LICENSE.md".
 *
 */

/* ***************************************************************
 * This code was auto generated by ClassStudio v0.4.0.           *
 *                                                               *
 * https://github.com/joao-neves95/ClassStudio                   *
 *                                                               *
 * ***************************************************************
 */

export class GeneratorDTO {

  /**
   *
   * @param input The input code. This should be set to null, if the input are multiple files.
   * @param inputAreFiles Whether if the input are files or directories.
   * @param inputSourceFiles The input file paths.
   */
  constructor( input: string | null, inputType: number = -1, inputAreFiles: boolean = false, inputSourceFiles: string[] = [] ) {
    this.Input = input;
    this.InputType = inputType;
    this.InputAreFiles = inputAreFiles;
    this.InputSourceFiles = inputSourceFiles;
  }

  public Input: string | null;
  public InputType: number | null;
  public InputAreFiles: boolean;
  public InputSourceFiles: string[];
}
