/*
 * Copyright (c) 2019-2020 João Pedro Martins Neves (shivayl) - All Rights Reserved.
 *
 * ClassStudio is licensed under the GPLv3.0 license (GNU General Public License v3.0),
 * located in the root of this project, under the name "LICENSE.md".
 *
 */

/* ***************************************************************
 * This code was auto generated by ClassStudio v0.4.0.           *
 *                                                               *
 * https://github.com/joao-neves95/ClassStudio                   *
 *                                                               *
 * ***************************************************************
 */

export class SelectDirectoryDTO {

  constructor( selectDiretory: boolean = true ) {

    if ( selectDiretory ) {
      this.SelectDirectory = true;
      this.SelectFiles = false;

    } else {
      this.SelectFiles = true;
      this.SelectDirectory = false;
    }

  }

  public SelectFiles: boolean;
  public SelectDirectory: boolean;

}
