/*
 * Copyright (c) 2019-2020 João Pedro Martins Neves (shivayl) - All Rights Reserved.
 *
 * ClassStudio is licensed under the GPLv3.0 license (GNU General Public License v3.0),
 * located in the root of this project, under the name "LICENSE.md".
 *
 */

/* ***************************************************************
 * This code was auto generated by ClassStudio v0.2.0.           *
 *                                                               *
 * https://github.com/joao-neves95/ClassStudio                   *
 *                                                               *
 * ***************************************************************
 */

export enum LangType {
    XML = 1,

    CSharp = 2,

    TypeScript = 3,

    JavaScript = 4,

    JSON = 5
}

export function numberToLangTypeLabel(langTypeId: number) {
    switch (langTypeId) {
        case 1:
            return 'XML';

        case 2:
            return 'CSharp';

        case 3:
            return 'TypeScript';

        case 4:
            return 'JavaScript';

        case 5:
            return 'JSON';

        default:
            return '';
    }
}

export function langTypeLabelToLangId(langTypeLabel: string): number {
    switch (langTypeLabel) {
        case 'XML':
            return 1;

        case 'CSharp':
            return 2;

        case 'TypeScript':
            return 3;

        case 'JavaScript':
            return 4;

        case 'JSON':
            return 5;

        default:
            return -1;
    }
}
